services:
  - type: web
    name: 26march
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -e .
    startCommand: gunicorn app:app
    autoDeploy: true
    rootDir: backend
    branch: backend
    healthCheckPath: /health
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: GROQ_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "https://two6march-1.onrender.com,http://localhost:3000"
      - key: DEBUG
        value: "False"
      - key: PORT
        value: "10000" 