services:
  - type: web
    name: backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.11
      - key: GROQ_API_KEY
        sync: false
      - key: SERPER_API_KEY
        sync: false
      - key: ALLOWED_ORIGINS
        value: "*"
      - key: DEBUG
        value: "False" 